config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'

  get 'tasks/:id', to: 'tasks#show', as: 'task'

  get 'task/new', to: 'tasks#new'

  post 'tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'

  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Update your tasks</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>


  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>These are all your tasks</h1>


<ul>
  <% @tasks.each do |task| %>
  <li>
    <h3> <%= link_to task.name, task_path(task) %> </h3>
    <p> <%= task.description %> </p>
    <h5> <%= task.deadline %> </h5>
    <p> <%= task.mark %> </p>
    <p> <%= link_to "Update the task" , edit_path(task) %> </p>
    <%= link_to "Delete the task" , task_path(task), method: :delete %>

  </li>
  <% end  %>
</ul>


<h2> <%= link_to "Create a new task", task_new_path %> </h2>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>


  <%= f.submit %>

<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.name %></h1>

<h4> <%= @task.description %></h4>

<h5> <%= link_to "List all tasks", root_path %></h5>